### ISSUE TITLE
[DE004] uinames.com - net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by tomejzen** [krzysiekprzekwas/online-shooter#27]
After starting server and entered web client I see this error:

![image](https://user-images.githubusercontent.com/11985426/47032995-02e87380-d174-11e8-970c-5bb5161646d8.png)

**Comment by krzysiekprzekwas** [comment]
Is it happening locally or on UAT?

**Comment by krzysiekprzekwas** [comment]
It is related to Client side add blocker. We'll need separate user story for such scenario.

Btw don't be scam. Let website owners earn some money
