### ISSUE TITLE
Config not synchronized with client

### ISSUE THREAD

**Issue by tomejzen** [krzysiekprzekwas/online-shooter#48]
Config on client side looks like this:

![image](https://user-images.githubusercontent.com/11985426/47377763-6fc0b800-d6f6-11e8-99c4-21fa717c4240.png)

We want to have readable keys and values.
Also I can see some unused variables like: jumP_POWER.

**Comment by krzysiekprzekwas** [comment]
Issue solced in Refactor #1 #51
